/**
 * Created by tushar on 4/2/16.
 */
angular.module("newApp").factory('NewMessage',function($resource,serverConfig){
    return $resource(serverConfig.address+'api/message?user_id=:user_id',{user_id:"@user_id",package_id:"@package_id",participant_id:"@participant_id"},
        {
        getParticipantsUnread:{
            method:"GET",
            url:serverConfig.address+"/api/UnreadMessageParticipants/:user_id/"
        },
        getParticipantsAll:{
            method:"GET",
            url:serverConfig.address+"/api/message?user_id=:user_id"
        },
        getMessages:{
            method:'GET',
            url:serverConfig.address+'/api/message/:user_id/:participant_id'
        }
        ,getPackageMessages:{
            method:'GET',
            url:serverConfig.address+'/api/message/:user_id/:participant_id?package_id=:package_id'
        },
        getNumberOfNewMessages:{
            method:"GET",
            url:serverConfig.address+"/api/NumberOfUnreadMessage/:user_id/"
        }
            ,
        sendMessage:{
            method:"POST",
            url:serverConfig.address+"/api/message/"
        }
    });
});
