/**
 * Created by tushar on 24/12/15.
 */
angular.module("newApp").factory("ZoloCollection",function($resource,serverConfig){
return $resource(serverConfig.address+'api/collection?user_id=:user_id',{user_id:"@user_id",id:"@id"},{
    addPackage1:{
        method:"POST",
        url :serverConfig.address+'api/collection/addPackages'
        },
    removePackage:{
        method:"POST",
        url:serverConfig.address+'api/collection/removePackages'
        },
    getCollection:{
        url:serverConfig.address+'api/collection/:id?include=Packages',
        method:"GET",
        },
    deleteCollection:{
        url:serverConfig.address+'api/collection/:id',
        method:"DELETE",
    },
    addCollection:{
        url:serverConfig.address+'api/collection/',
        method:"POST",
        }
    }/*,{
    update:{
        method:"PUT"
    },
    get:{
        method:"GET",
        url:serverConfig.address+'api/getMessages?user_id_1=:id1&user_id_2=:id2'
    },
    getSendersId:{
        method:'GET',
        url:serverConfig.address+'api/getMessageSenders/:id'
    },
    getReceiversId:{
        method:'GET',
        url:serverConfig.address+'api/getMessageReceivers/:id'
    }
}*/);
});
